#!/bin/bash
set -x

if [[ "$USER" -ne "pi" ]]
  then echo "Please do not run as root"
  exit
fi

SERVICE_PATH=/home/pi/ft
SERVICE_PYTHON="sudo $SERVICE_PATH/ft-venv/bin/python3"

cd $SERVICE_PATH

$SERVICE_PYTHON -u blink.py &

while ! systemctl --no-pager status network-online.target; do
    sleep 1
done

if [ ! -f init_python_libs ]; then
    touch init_python_libs
    $SERVICE_PYTHON -m pip install gpiozero firebase_admin google-cloud-firestore rpi_ws281x adafruit-circuitpython-neopixel pygame
fi

$SERVICE_PYTHON -u main.py
