#!/bin/bash
set -x

if [[ "$USER" -ne "pi" ]]
  then echo "Please do not run as root"
  exit
fi

cd /home/pi/ft

sudo /usr/bin/python3 -u blink.py &

while ! systemctl --no-pager status network-online.target; do
    sleep 1
done

cd /home/pi/ft

if [ ! -f init_python_libs ]; then
    touch init_python_libs
    sudo python3 -m pip install gpiozero firebase_admin rpi_ws281x adafruit-circuitpython-neopixel
fi

sudo /usr/bin/python3 -u main.py
